# Database Connection
# IMPORTANT: Replace the entire line below with your External URL from Render
spring.datasource.url=postgresql://smartquiz_db_daksha_user:vN3BCZk7rO5ZpRwxuqIhMnSOrrq3Huk7@dpg-d219p3qdbo4c73ej4eig-a.oregon-postgres.render.com/smartquiz_db_daksha

# JPA / Hibernate Configuration
# This setting tells Hibernate to update the database schema based on your entities
spring.jpa.hibernate.ddl-auto=update
# This setting will show the SQL queries in the console, which is useful for debugging
spring.jpa.show-sql=true
# This tells Spring which SQL dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# This tells Spring to initialize the database with our data.sql file
spring.sql.init.mode=always