# Database Connection
# CONVERTED to the standard JDBC format
spring.datasource.url=jdbc:postgresql://oregon-postgres.render.com/smartquiz_db_daksha
spring.datasource.username=smartquiz_db_daksha_user
spring.datasource.password=vN3BCZk7rO5ZpRwxuqIhMnSOrrq3Huk7

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always